### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by MaeseppTarvo** [artisanry/braintree#12]
Hey I am getting the following error while executing the `composer require faustbrian/laravel-braintree` command:

> Your requirements could not be resolved to an installable set of packages.

So what are the requirements?

This is the log I get:

<img width="1317" alt="screen shot 2017-11-02 at 14 06 39" src="https://user-images.githubusercontent.com/8416295/32325315-1d47ceba-bfd7-11e7-86cc-173e9e2ce74e.png">

To fix this, you gotta use version "graham-campbell/manager": "^8.0"

**Comment by user00265** [comment]
Hi,

graham-campbell/manager has no version 8.0, but I submitted PR #14 (now approved by @faustbrian) which should fix this.

Have a good day!

**Comment by faustbrian** [comment]
This should be resolved in https://github.com/artisanry/braintree/releases/tag/4.0.0.

Make sure that you lock your release to `4.x` if you don't want to be affected by the changes of https://github.com/artisanry/braintree/releases/tag/5.0.0 and https://github.com/artisanry/braintree/releases/tag/5.1.0.
